spring:
  application:
    name: eureka-service
server:
  port: 8300

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8301
    random-data:
      path: /random-data/**
      url: http://localhost:8302/
    analyze-data:
      path: /analyze-data/**
      url: http://localhost:8303/
